### ISSUE TITLE
Hell should only have Evil altars

### ISSUE THREAD

**Issue by john-science** [john-science/HCSS#3]
There are no altars in Hell, so remove them all.

That is all altars after #2 , where provide a small set of them.

* [X] Players can choose 1 of 4 good gods in a Temple on D1 now.
* [X] Players can NOT interact with any other altars in game.
* [X] All other alters in game look more evil now.
* [x] Make the evil altars look more evil.
* [x] Can we rename the evil gods to sound more evil?
* [x] Good altars should not be spawning outside temple
        - Can we change the `*.des` files to have a character good altars and one for evil altars?

**Comment by john-science** [comment]
Or... remove all but the "evil god" altars from the game. And ensure that when a player tries to use such an altar they get the "This god does not accept people such as you" error that is currently thrown due to species-incompatibility with a god.

**Comment by john-science** [comment]
I have disconnected all altars in the game from being usable except the Good Gods. So that's a good start.

The way I think this would work now is:

1. The player should choose their god at the beginning of the game. Say, the arrival vault should be the only room not themed like Hell, and the player has a choice of the 3 good altars at that spot.
2. Remove the Altar level that pops up D4-D11 or whatever.
3. Remove all but the truly evil altars for the rest of the game. This is Hell, after all, why would the the demons there worship anything but the most terrible gods?
4. Reconsider which goods should be truly "good" or "evil", and fix accordingly.
5. Simplify the god/altar/pray logic to be simply split between "good" and "evil".
  a. Consider removing the middle-ground gods entirely.

**Comment by john-science** [comment]
This ticket is almost done. 

* Players can choose 1 of 4 good gods in a Temple on D1 now.
* Players can NOT interact with any other altars in game.
* All other alters in game look more evil now.

Left to do:

* Make the evil altars look _more_ evil.
* Can we rename the evil gods to sound more evil?

**Comment by john-science** [comment]
Close enough
